environment:
  matrix:
    - nodejs_version: 12
install:
  - ps: Install-Product node $env:nodejs_version
  - set CI=true
  - npm i -g npm
  - set PATH=%APPDATA%\npm;%PATH%
  - npm i
matrix:
  fast_finish: true
build: off
version: '{build}'
shallow_clone: true
clone_depth: 1
test_script: npm t
